### ISSUE TITLE
[BUG] Module not activating on 3.3.1 ruleset

### ISSUE THREAD

**Issue by KrisCarlos** [krbz999/babonus#445] opened 2024-08-25 20:57 UTC
Version 11.1.1 will not allow me to activate the module after moving to version 3.3.1 with v11 of Foundry.  

When trying to enable the module, the message in the "Manage Modules" screen is "This module requires a maximum system version of 3.2.9 but your version is 3.3.1.

The documentation here would suggest it will work on v11 with the most recent ruleset.

**Comment by krbz999** [comment] 2024-08-25 20:58
Duplicate of #440 and #442.

**Closed by krbz999** 2024-08-25 20:58 UTC
Labels: duplicate

**Comment by krbz999** [comment] 2024-08-25 21:01
You will have to update to version 12 of the core software.
