### ISSUE TITLE
Version 11.11.0 set Minimum DnD5e version to pre-release 3.2 [BUG]

### ISSUE THREAD

**Issue by PointFrankRange** [krbz999/babonus#414] opened 2024-05-21 14:19 UTC
**Describe the bug**
It appears that the latest version of Build-A-Bonus set the Minimum DnD5e version to the pre-release version 3.2.0 and broke the module in the currently released version 3.1.2.

**Screenshots**

**Build-A-Bonus Release Notes:**

![image](https://github.com/krbz999/babonus/assets/68871430/7f79c238-172f-42de-8b10-3dee27606615)

**DND5E Release Details:**

![image](https://github.com/krbz999/babonus/assets/68871430/3d4fb8cc-d7da-45f2-b1cd-4447c314e025)

**FoundryVTT Module Error:**

![image](https://github.com/krbz999/babonus/assets/68871430/5067a1fe-f8e5-4f61-b952-4852cf9d37d6)

**Comment by krbz999** [comment] 2024-05-21 14:20
Not a bug. This issue makes no sense. It is exactly as described. Closing.

**Closed by krbz999** 2024-05-21 14:20 UTC
