### ISSUE TITLE
If a bonus is embedded on an ActiveEffect, defer to the state of the effect rather than the origin of the effect to determine whether the bonus is suppressed.

### ISSUE THREAD

**Issue by maxobremer** [krbz999/babonus#327] opened 2023-12-15 22:00 UTC
**Describe the bug**
When a bonus to for example cold damage is applied to a custom effect in dfred convenient effect, the bonus is not factored into the roll.

**To Reproduce**
1. Get an empty world with just BaB and DFred's Convenient Effect active
2. Make a custom effect in dfred that has BaB bonus to for example cold damage rolls
3. roll with an actor that deals cold damage (for my tests i used an acolyte and made its club deal cold damage
4. Notice no cold damage buff

**Expected behavior**
I expect the cold damage to receive the buff when the buff comes from a custom convenient effect just like when it comes from a normal active effect.

**Screenshots**
![image](https://github.com/krbz999/babonus/assets/86924581/190320b7-49a4-4379-be49-dcd37afeaf27)

**A** has a normal active effect with a BaB while **B** has a custom DFred's Convenient Effect with the same BaB

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.5.1
- DFreds Convenient Effects version: 6.0.0
- Foundry core version and build: 11 build 315
- DnD5e version: 2.4.1
- Other modules disabled? Yes/No: No (besides those necessary which are libwrapper and socketlib)

**Additional context**
As i was writing this I saw there was a new BaB version, however I tried testing it for this issue but got the following error when i tried to update:
![image](https://github.com/krbz999/babonus/assets/86924581/a9c254ee-99f1-4e57-8752-a34796a77d88)

**Comment by maxobremer** [comment] 2023-12-15 22:09
The issue with updating BaB as mentioned in the additional context has been resolved as of Build-a-Bonus version: 11.6.1
The other issue still remains as of 11.6.1

**Comment by krbz999** [comment] 2023-12-15 22:11
It's hard to determine the issue here. I'm inclined to believe the effect from the other module is simply not applied at all, or has some erroneous data, or the module is overriding some core behaviour.

Are there errors?

**Comment by maxobremer** [comment] 2023-12-15 22:28
No errors at all, the custom dfred convenient effect is applying a bonus to melee weapon attack correctly here, but the attached BaB is not being applied
![image](https://github.com/krbz999/babonus/assets/86924581/d5b3cde7-3dd0-4acf-9f2c-17b79c4edffd)


Here are screenshots of the other tabs, that matter, of the specfic BaB used for the test
![image](https://github.com/krbz999/babonus/assets/86924581/bce4bfdd-fd2b-431d-b484-aeb5eb59eac4)
![image](https://github.com/krbz999/babonus/assets/86924581/29c5e0cf-a1d3-4642-9eb0-fd3a0915f0a8)

It could be that the issue lies with Dfred, my first instinct was that it lies with BaB though, hence the issue here

**Comment by maxobremer** [comment] 2023-12-15 22:29
Got two warnings, but those seem unrelated
![image](https://github.com/krbz999/babonus/assets/86924581/b62ef796-59dc-46d1-a9d4-67d3e354e02e)

**Comment by krbz999** [comment] 2023-12-15 22:30
Does the bonus exist on the effect after the effect has been added to the actor?
If so, does the bonus apply after adding the effect to the actor and disabling all modules but babonus?

**Comment by maxobremer** [comment] 2023-12-15 22:35
The BaB seems to be there when i edit/look at the effect on the actor (applied using dfred, so its a custom dfred effect, also the other BaB effect is to look if attack roll BaB bonusses have issues as well, they do)

issue remains when BaB is the only module active
![image](https://github.com/krbz999/babonus/assets/86924581/90b91e66-2cb4-4d09-9509-c0538642cbf4)

**Comment by krbz999** [comment] 2023-12-15 22:45
Interesting. Can you run this macro:
```js
const effect = await fromUuid("uuid of the effect on the actor with the bonus");
console.warn(effect.toObject());
```
and then upload a txt file here with the log output.

**Comment by maxobremer** [comment] 2023-12-15 22:47
Sure, with only BaB active or with both it and Dfred?

**Comment by krbz999** [comment] 2023-12-15 22:50
It should hopefully not matter.

**Comment by maxobremer** [comment] 2023-12-15 22:51
[Log for Zhell with Dfred active.txt](https://github.com/krbz999/babonus/files/13690242/Log.for.Zhell.with.Dfred.active.txt)
[Log for Zhell only BaB active.txt](https://github.com/krbz999/babonus/files/13690243/Log.for.Zhell.only.BaB.active.txt)

Here are both

**Comment by krbz999** [comment] 2023-12-15 22:52
The uuid is gotten from right-clicking the book icon in the effect's header. I will only need to see the logged object.

**Comment by maxobremer** [comment] 2023-12-15 22:56
UUID from the active effect on the actor: REkL3KFhR15DwrXu

Is this how you want the log? right clicked in console menu and clicked save as
[Log for Zhell only BaB active version 2.txt](https://github.com/krbz999/babonus/files/13690251/Log.for.Zhell.only.BaB.active.version.2.txt)

**Comment by krbz999** [comment] 2023-12-15 22:56
No, the logged object from the above macro is all I care about.

**Comment by maxobremer** [comment] 2023-12-15 22:57
Scene.WZtDeDeQRpDydVdB.Token.4a2SvY988ivJ85pr.Actor.p2NncMTIpaHK9iOx.ActiveEffect.REkL3KFhR15DwrXu

**Comment by maxobremer** [comment] 2023-12-15 22:58
[Log for Zhell only BaB active version 3.txt](https://github.com/krbz999/babonus/files/13690261/Log.for.Zhell.only.BaB.active.version.3.txt)
this should be what you want

**Comment by maxobremer** [comment] 2023-12-15 22:59
sorry i got a bit confused and without thinking just copied the macro and ran it, without checking what it did

**Comment by krbz999** [comment] 2023-12-15 22:59
Please copy the full logged object. Again, you can right-click this object (it will be in a yellow warning message), and then paste it into a txt file.

**Comment by maxobremer** [comment] 2023-12-15 23:00
[Log for Zhell only BaB active version 4.txt](https://github.com/krbz999/babonus/files/13690268/Log.for.Zhell.only.BaB.active.version.4.txt)
this then?

**Comment by krbz999** [comment] 2023-12-15 23:12
Yes, that's correct. I'm sadly not able to reproduce any issue on my end after creating a copy of this effect on a token's actor. The token is not linked, same as in your screenshot with the Acolyte.

**Comment by krbz999** [comment] 2023-12-15 23:16
Actually no, I take it back. This effect has an `origin` pointing to an item somewhere in your world. The bonus will not be applied if said item is not equipped (or not attuned).

**Comment by maxobremer** [comment] 2023-12-15 23:20
[test.zip](https://github.com/krbz999/babonus/files/13690339/test.zip)

I mean, here is a zip of my test world, maybe that works?

**Comment by maxobremer** [comment] 2023-12-15 23:21
like i completely deleted my test world, made a new one, had the same issue. 
went to C:\Users\ignorethisbitAppData\Local\FoundryVTT\Data\worlds and zipped up the folder named test using winzip, which i just installed for this

**Comment by krbz999** [comment] 2023-12-15 23:25
This does confirm this being the case. The origin of the effect is the 'Custom Convenient Effects' item in your item directory, which has no actor.

I think a case could easily be made for unowned items not having their bonuses suppressed.

**Comment by maxobremer** [comment] 2023-12-15 23:28
what item in my item directory? Cause i dont see one
![image](https://github.com/krbz999/babonus/assets/86924581/a2285148-06e1-443c-9802-650c802db0c8)

**Comment by maxobremer** [comment] 2023-12-15 23:29
nevermind it appeared when i disabled dfred and just had BaB active

**Comment by krbz999** [comment] 2023-12-15 23:55
I think two changes are in order to simplify things a little bit.

1: If the bonus is on an effect, it should not matter what state the origin item is in. We simply defer to whether the effect is modifying the actor currently (i.e., it is neither suppressed nor disabled). I think this makes sense since an item can grant an effect to another actor and then be unequipped; this does not normally turn the effect inactive, and the module should follow that example set by the system.

2: If still, somehow, the bonus originates from an item, and said item is not owned by an actor, then the bonus is not suppressed. This should not be needed with (1), but it still makes sense to do and is easy.

If however the origin of the bonus is an owned item, we still check whether the item is equipped/attuned (or 'crewed' in the case of vehicles) as we do currently. Auras, for example.

**Comment by krbz999** [comment] 2023-12-16 00:02
Since the module behavior was not in line with system behavior, I am inclined to mark this as a bug.

**Closed by krbz999** 2023-12-16 00:02 UTC
Labels: bug
