### ISSUE TITLE
[BUG] Doesn't support server being at a custom path. 

### ISSUE THREAD

**Issue by Fneuch** [krbz999/babonus#410] opened 2024-05-14 03:11 UTC
**Describe the bug**
The css doesn't work when "routePrefix" is set to something. 

The background url set in class: .babonus.dnd5e2  return a 404 when the application is started with a routePrefix.

**To Reproduce**
1. In setup, go to application configuration
2. change the "routePrexix" option to anything.
3. start a world.
4. Go to Build a bonus in the actor sheet. 
5. see the error in the console.

**Expected behavior**
No error in the console and the background image is shown properly.

**Screenshots**
![image](https://github.com/krbz999/babonus/assets/9579799/9979b6be-dd95-49fe-9992-1419c6538a1b)

![image](https://github.com/krbz999/babonus/assets/9579799/3ab3960e-25a8-41bf-8810-5643d32ba965)

**Setup**
Describe your foundry setup.
- Build-a-Bonus version:
- Foundry core version and build:
- Other modules disabled? No

**Additional context**

**Comment by krbz999** [comment] 2024-05-14 12:46
Nothing here looks incorrect.

**Comment by krbz999** [comment] 2024-06-26 11:39
I was not able to reproduce this, so I'll be closing it as nonrepro. I believe it to be a system issue if anything given what is failing to be found with a routeprefix. Feel free to comment if there are other steps to reproduce the problem.

**Closed by krbz999** 2024-06-26 11:39 UTC
Labels: nonrepro
