### ISSUE TITLE
Feature Request: A type that can serve similarly to a bonus to Armor Class

### ISSUE THREAD

**Issue by rinnocenti** [krbz999/babonus#73] opened 2022-11-11 22:03 UTC
Mainly to use in conjunction with auras, being able to apply bonus AC on yourself and others around you would be a great addition

**Comment by krbz999** [comment] 2022-11-16 23:45
While I can immediately see the use case for this, it is not within the current scope of the module (in an attempt to keep the computation light) to actively calculate aura ranges on every token movement or even perform asynchronous operations, which a feature like this would require.

I'll take this request into consideration in the future if a solution that is cleaner than reading every token movement and performing Active Effects manipulation presents itself.

**Comment by krbz999** [comment] 2023-12-26 19:09
> I'll take this request into consideration in the future if a solution that is cleaner than reading every token movement and performing Active Effects manipulation presents itself.

No such thing has happened, and it is unlikely any such thing ever will. Cannot do anything but close as duplicate of #38, which is the only reasonable alternative.

**Closed by krbz999** 2023-12-26 19:09 UTC
Labels: enhancement
