### ISSUE TITLE
[BUG] Update to module.json 5e min system incorrect

### ISSUE THREAD

**Issue by Aelinon10** [krbz999/babonus#416] opened 2024-05-22 03:10 UTC
I'm going to keep it short and sweet:  looks like you fat-fingered the module dependency for the system.  I assume you meant minimum should be 3.1.2 not 3.2.0, which doesn't yet exist.  Module cannot be enabled due to this.  Someone already commented on the change 5 days ago.
![image](https://github.com/krbz999/babonus/assets/42057390/f354d71c-c98e-4312-9704-aa44112fdbdd)

**Comment by noreaga** [comment] 2024-05-22 05:30
+1 broken here as well

**Comment by FurtherV** [comment] 2024-05-22 05:33
Its not broken. That version is only for dnd 3.2 and its pre release. Just revert the update.

**Comment by Aelinon10** [comment] 2024-05-22 08:06
Workaround until we hear back from Zhell - you can manually edit the module.json on your Foundry installation: `"...Foundry data path...\Data\modules\babonus\module.json"`  find 
`"systems": [
      {
        "id": "dnd5e",
        "type": "system",
        "compatibility": {
          "minimum": "3.2.0",
          "maximum": "3.2.9"
        }
      }`
and change the "minimum" value to "3.1.2".

Alternatively, you can roll back manually by replacing the contents of the `babonus` module folder with the prior version module.zip at [https://github.com/krbz999/babonus/releases/tag/v11.10.6](https://github.com/krbz999/babonus/releases/tag/v11.10.6) per Foundry's instructions under "installing modules manually": [https://foundryvtt.com/article/modules/](https://foundryvtt.com/article/modules/)

**Comment by InnilToo** [comment] 2024-05-22 08:08
This issue is a duplicate of https://github.com/krbz999/babonus/issues/413 https://github.com/krbz999/babonus/issues/414 https://github.com/krbz999/babonus/issues/415.

**Comment by krbz999** [comment] 2024-05-22 08:09
5

**Closed by krbz999** 2024-05-22 08:09 UTC

**Comment by krbz999** [comment] 2024-05-22 08:15
> > Its not broken. That version is only for dnd 3.2 and its pre release. Just revert the update locally on your Installation.
> 
> I will wait for Zhell to respond - bugs happen and this one appears to be a very easy fix. Maybe they meant to fork? Dunno, totally up to the dev. I appreciate your position, but I don't see you as a contributor to this code base anywhere and by your logic a breaking change that is auto-deploying globally should be resolved by the end user. "Just revert the update locally on your Installation." Honestly!

This is not OK and seems to be founded in misinformation.

Module updates do not automatically install themselves. Nothing in foundry installs itself without users prompting it.

The fact of the matter is that the update was available, you went and saw the release notes that said 3.2 was required, and you decided to update regardless. That is on you.

Previous releases can be installed manually by copying the manifest link.

I reserve the right to assume some level of accountability on the end-user to know how their installed software works.
